name: linus_player
description: "Linus - High-Fidelity Offline Device Music Player for Android"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.43
  audio_service: ^0.18.17
  audio_session: ^0.1.21
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  cached_network_image: ^3.4.1
  rxdart: ^0.28.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
